openapi: "3.1.0"
info:
  title: "ratatouille_backend API"
  description: "ratatouille_backend API"
  version: "1.0.0"
servers:
  - url: "https://ratatouille_backend"
paths:
  /:
    get:
      description: ""
      responses:
        "302":
          description: "Found <br> Redirect"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "/api"
  /api:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/EmptySuccessResponse"
  /api/users/{userId}:
    delete:
      description: ""
      parameters:
        - name: "userId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "500":
          description: "Internal Server Error <br> ✅ Print full stack trace"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDetailResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "409":
          description: "Conflict"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
    get:
      description: ""
      parameters:
        - name: "userId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDetailResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "409":
          description: "Conflict"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "500":
          description: "Internal Server Error <br> ✅ Print full stack trace"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
    post:
      description: ""
      parameters:
        - name: "userId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "500":
          description: "Internal Server Error <br> ✅ Print full stack trace"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDetailResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "409":
          description: "Conflict"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
  /api/users/me:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "409":
          description: "Conflict"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "500":
          description: "Internal Server Error <br> ✅ Print full stack trace"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
    patch:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProfileRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "409":
          description: "Conflict"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "500":
          description: "Internal Server Error <br> ✅ Print full stack trace"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
  /api/users/me/cover-picture:
    post:
      description: ""
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "500":
          description: "Internal Server Error <br> ✅ Print full stack trace"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "409":
          description: "Conflict"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
  /api/users/me/profile-picture:
    post:
      description: ""
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "500":
          description: "Internal Server Error <br> ✅ Print full stack trace"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserResponse"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
        "409":
          description: "Conflict"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponse"
components:
  schemas:
    Void:
      type: "object"
      properties: { }
    FailureResponse:
      type: "object"
      properties:
        success:
          type: "boolean"
        message:
          type: "string"
          nullable: true
        data:
          nullable: true
          $ref: "#/components/schemas/Void"
      required:
        - "success"
    EmptySuccessResponse:
      type: "object"
      properties:
        success:
          type: "boolean"
        message:
          type: "string"
          nullable: true
        data:
          nullable: true
          $ref: "#/components/schemas/Void"
      required:
        - "success"
    UserDto:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        email:
          type: "string"
        profilePictureUrl:
          type: "string"
          nullable: true
        coverPictureUrl:
          type: "string"
          nullable: true
        bio:
          type: "string"
          nullable: true
        isEmailVerified:
          type: "boolean"
        createdAt:
          type: "string"
          format: "date-time"
      required:
        - "id"
        - "name"
        - "email"
        - "isEmailVerified"
        - "createdAt"
    UserDetailDto:
      type: "object"
      properties:
        user:
          $ref: "#/components/schemas/UserDto"
        isMe:
          type: "boolean"
        isFollowing:
          type: "boolean"
        followerCount:
          type: "integer"
          format: "int64"
        followingCount:
          type: "integer"
          format: "int64"
      required:
        - "user"
        - "isMe"
        - "isFollowing"
        - "followerCount"
        - "followingCount"
    UserDetailResponse:
      type: "object"
      properties:
        success:
          type: "boolean"
        message:
          type: "string"
          nullable: true
        data:
          $ref: "#/components/schemas/UserDetailDto"
      required:
        - "success"
        - "data"
    UserResponse:
      type: "object"
      properties:
        success:
          type: "boolean"
        message:
          type: "string"
          nullable: true
        data:
          $ref: "#/components/schemas/UserDto"
      required:
        - "success"
        - "data"
    UpdateProfileRequest:
      type: "object"
      properties:
        name:
          type: "string"
          nullable: true
        bio:
          type: "string"
          nullable: true